source 'https://rubygems.org'

gem 'grape'
gem 'sqlite3'
gem 'rack-contrib'
gem 'bootstrap-sass', '~> 3.1.1.1'
gem 'compass', '~> 0.12.6'
gem 'warden'
gem 'bcrypt'
gem "password_strength"
gem 'rack-cors'
gem 'activerecord'
gem 'rack-test'
gem 'rspec'
gem 'capybara'
