source 'https://rubygems.org'

gem 'grape'
gem 'sqlite3'
gem 'rack-contrib'
gem 'warden'
gem 'bcrypt'
gem "password_strength"
gem 'rack-cors'
gem 'activerecord'

group :development, :test do
  gem 'rack-test'
  gem 'rspec'
  gem 'capybara'
  gem 'guard'
  gem 'guard-rspec', require: false
end